version: "3.8"

services:
  mysql_db:
    image: mysql:8.0.28
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3307:3306
    volumes:
      - mysqldb_data:/var/lib/mysql

volumes:
  mysqldb_data:
